对难测和启动器常见问题的补充
WForst-Breeze/PCL2-1930 pull request #12
Opened 2024-03-27 04:47 UTC by wuliaodexiaoluo

## 难检增加
- ModLoader 与 OptiFine 同时安装导致启动失败
## 常见问题增加
- 修改整合包 Forge 版本

2024-03-27 11:42 UTC, WForst-Breeze requested changes
稍微需要一点小调整，非常感谢——！

2024-03-27 11:42 UTC, WForst-Breeze commented on README.md
> + | 安装整合包时允许修改 Forge 版本 | 修改加载器版本可能会导致兼容性问题，不予考虑，请联系整合包作者解决这个问题 | #3568
句末添加句号

2024-03-27 11:42 UTC, WForst-Breeze commented on README.md
> + | 同时安装 OptiFine 和 ModLoader 导致游戏无法正常加载 | 因为 Optifine 过于激进的优化手段，导致 OptiFine 和 ModLoader 之间存在非常严重的兼容性问题，请考虑只安装 OptiFine 或只安装 Forge，亦或是使用其他 Mod 替代 | #3258 #3566 #3573
句末添加句号；
将此条目移动至 Minecraft 常见问题部分下。

2024-03-27 14:33 UTC, rumengchuxing062 commented on README.md
> + | 同时安装 OptiFine 和 ModLoader 导致游戏无法正常加载 | 因为 Optifine 过于激进的优化手段，导致 OptiFine 和 ModLoader 之间存在非常严重的兼容性问题，请考虑只安装 OptiFine 或只安装 Forge，亦或是使用其他 Mod 替代 | #3258 #3566 #3573
我看到了手快没有大写的 F

2024-03-27 23:38 UTC, WForst-Breeze requested changes

2024-03-27 23:38 UTC, WForst-Breeze commented on README.md
> +  | 同时安装 OptiFine 和 ModLoader 导致游戏无法正常加载 | 因为 OptiFine 过于激进的优化手段，导致 OptiFine 和模组加载器之间存在非常严重的兼容性问题，请考虑只安装 OptiFine 或只安装模组加载器，亦或是使用其他 Mod 替代。 | #3258 #3566 #3573
ModLoader -> 模组加载器

2024-03-28 04:39 UTC, allMagicNB requested changes
再改改吧……

2024-03-28 04:39 UTC, allMagicNB commented on README.md
> +
改啥了？

2024-03-28 04:39 UTC, allMagicNB commented on README.md
> +  | 同时安装 OptiFine 和模组加载器导致游戏无法正常加载 | 因为 OptiFine 过于激进的优化手段，导致 OptiFine 和模组加载器之间存在非常严重的兼容性问题，请考虑只安装 OptiFine 或只安装模组加载器，亦或是使用其他 Mod 替代。 | #3258 #3566 #3573
多了个空格……

2024-03-28 05:54 UTC, allMagicNB commented
……没搞好标啥？

2024-03-28 05:54 UTC, wuliaodexiaoluo commented on README.md
> +
这个是调整了下面这个问题的位置
- ModLoader 与 OptiFine 同时安装导致启动失败

2024-03-28 05:54 UTC, wuliaodexiaoluo commented on README.md
> +  | 同时安装 OptiFine 和模组加载器导致游戏无法正常加载 | 因为 OptiFine 过于激进的优化手段，导致 OptiFine 和模组加载器之间存在非常严重的兼容性问题，请考虑只安装 OptiFine 或只安装模组加载器，亦或是使用其他 Mod 替代。 | #3258 #3566 #3573
手快了抱歉。。。

2024-03-28 05:55 UTC, wuliaodexiaoluo commented
> ……没搞好标啥？

有个不用改

2024-03-28 11:34 UTC, WForst-Breeze approved these changes

2024-03-28 13:20 UTC, rumengchuxing062 approved these changes

2024-03-30 13:24 UTC, merged