难检增加 32 位系统 Bug 说明
WForst-Breeze/PCL2-1930 pull request #25
Opened 2024-04-13 04:51 UTC by wuliaodexiaoluo

因为迄今为止还没有 32 为系统出现 Bug，就先加难检了
如果后面多起来了再挪

2024-04-13 05:11 UTC, allMagicNB requested changes

2024-04-13 05:11 UTC, allMagicNB commented on README.md
> + | 关于 32 位系统下 PCL 问题 | 无法在 64 位系统下复现的 Bug 不予处理 | [#3649](https://github.com/Hex-Dragon/PCL2/issues/3649#issuecomment-2047054821)
不用超链接……
而且原话不是这样，你这样概括的话……
```suggestion
 | 关于 32 位系统下 PCL 问题 | 无法在 64 位系统下复现的 Bug 不予处理 | https://github.com/Hex-Dragon/PCL2/issues/3649#issuecomment-2047054821
```

2024-04-13 05:46 UTC, allMagicNB submitted a review, later dismissed

2024-04-13 06:43 UTC, WForst-Breeze commented
现在的 Minecraft 仅支持 64 位系统运行，大部分情况下，不会有人使用 32 位系统去尝试的。

综上所述，此内容搜索难度不高，关键词明确，出现频率较低，暂不考虑添加

感谢贡献！

2024-04-13 06:52 UTC, wuliaodexiaoluo commented
~好好好，一个个都是 Collaborator 和 Member 是吧，这么玩是吧~
犹豫就会败北.jpg

2024-04-14 23:09 UTC, JingHai-Lingyun requested changes
改成 `启动器后续发布的版本依然可以在32位系统上运行，但是不会再额外为 32 位进行修复和调整` 是否更加合适？

2024-04-14 23:19 UTC, wuliaodexiaoluo commented
改了

2024-04-14 23:20 UTC, JingHai-Lingyun approved these changes

2024-04-15 14:39 UTC, WForst-Breeze commented
措辞我会在周末重新组织一遍，周末 Merge，感谢贡献

2024-04-20 10:50 UTC, WForst-Breeze approved these changes

2024-04-20 10:50 UTC, merged

2024-04-21 00:15 UTC, wuliaodexiaoluo commented
allMagicNB 这货跟我说直接1贴超链接就行
最后 WForst-Breeze 还是改成了 Markdown 超链接。。。。

2024-04-21 00:19 UTC, JingHai-Lingyun commented
可以的话，尽量使用 \[#ID](XXX/ID#issuecomment-XXXX) 的形式来引用帖内特定的 Comment

2024-04-21 02:42 UTC, WForst-Breeze commented
直接粘也行，我这样干是为了让自己能看清楚点