增加#3202 有关拓展隐藏主题、自定义主题、背景图片功能的 Issue
WForst-Breeze/PCL2-1930 pull request #3
Opened 2024-02-01 12:14 UTC by allMagicNB

emm，前几天看到个关于自定义主题的 Issue ，刚好关了，加个反面例子
或者说我攒一大堆再交PR（？

2024-02-01 12:22 UTC, WForst-Breeze commented
> 或者说我攒一大堆再交PR（？

到时候直接继续 commit 就好

2024-02-01 12:24 UTC, allMagicNB commented
emm，我看看附近的 Issue ……

2024-02-01 13:11 UTC, WForst-Breeze requested changes

2024-02-01 13:11 UTC, WForst-Breeze commented on README.md
> + | 下载或安装资源时失败 | 请先尝试使用其他启动器下载，若使用后问题依然存在，则非 PCL 问题，请使用镜像源或检查您的网络环境，使用加速器或 VPN。如果确定网络环境无问题，可以更换“游戏Java”选项后再次尝试 |
展开更换成什么样子，引号前后添加空格，句末句号，如果要添加这个描述就加一下参考的 Issue

2024-02-01 13:44 UTC, allMagicNB commented
修好了，再看看？

2024-02-01 14:50 UTC, WForst-Breeze approved these changes

2024-02-01 14:51 UTC, merged

2024-02-01 14:56 UTC, WForst-Breeze commented
又去看了一下，时效性有点强，等新版本出来了这条表述可能会被删除🤔但写都写了还是先挂上好了，感谢贡献

2024-02-02 00:30 UTC, allMagicNB commented
> 又去看了一下，时效性有点强，等新版本出来了这条表述可能会被删除🤔但写都写了还是先挂上好了，感谢贡献

那个标题本身就是包括**安装**版本的，而PCL2安装时会使用`游戏Java`这个选项来运行`.jar`文件……
但这个 Issue 就是因为PCL2没能正确选择应该使用的 Java 造成的
以后可能 Mod Loader 更新又使用了低版本的 Java 没有的功能，然后又导致报错……
总之，先看看龙猫怎么修吧……