创建 GitHub Actions
WForst-Breeze/PCL2-1930 pull request #30
Opened 2024-04-19 15:09 UTC by Deep-Dark-Forest

本人对 GitHub Actions 还不太熟悉，可能会有语法错误
目前还没完全做好，先 Draft 了
**ToDo**
- [X] 当 PR 满足 “被 close ” 或 “被添加`× 拒绝`标签” 中的任意一个条件时执行 GitHub 
 Action 使其同时满足这两个条件
- [ ] 当 PR 满足 “被 Approve ” 或 “被添加`通过`标签” 中的任意一个条件时执行 GitHub  Action 使其同时满足这两个条件
- [ ]  当 PR  被 Merge  后自动添加“完成标签”

2024-04-19 15:46 UTC, hejiehao commented
https://github.com/uesteibar/reviewer-lottery

2024-04-20 00:48 UTC, Deep-Dark-Forest commented
> https://github.com/uesteibar/reviewer-lottery

好像没有问题？

2024-04-20 03:57 UTC, Deep-Dark-Forest commented
需要帮助......
![image](https://github.com/PCL-Community/PCL2-1930/assets/131975043/041e6970-d518-4c47-b7e1-29767c9003a6)

2024-04-20 05:11 UTC, hejiehao commented
> 需要帮助......
> ![image](https://github.com/PCL-Community/PCL2-1930/assets/131975043/041e6970-d518-4c47-b7e1-29767c9003a6)
> 

因为 Merge 也算 Closed……

2024-04-20 06:13 UTC, Deep-Dark-Forest commented
> > 需要帮助......
> > ![image](https://github.com/PCL-Community/PCL2-1930/assets/131975043/041e6970-d518-4c47-b7e1-29767c9003a6)
> > 
> 
> 因为 Merge 也算 Closed……

那我就加个 yml 让他自动改过来

2024-04-20 12:49 UTC, WorldHim requested changes

2024-04-20 12:49 UTC, WorldHim commented on .github/workflows/Reject.yml
> +        if: github.event.pull_request.state == 'closed' && !contains(github.event.pull_request.labels.*.name, '× 拒绝')
加一个 `github.event.pull_request.merged == false` 或许能修复？

2024-04-20 12:58 UTC, allMagicNB approved these changes

2024-04-21 00:40 UTC, Deep-Dark-Forest commented
现在已经没有任何问题喽，考虑merge？

2024-04-21 01:00 UTC, JingHai-Lingyun approved these changes

2024-04-21 01:05 UTC, allMagicNB approved these changes

2024-04-21 07:18 UTC, Deep-Dark-Forest commented
各位先等一等！我得改一改

2024-04-21 10:47 UTC, hejiehao commented on .github/workflows/Start.yml
> +  request_review:
```suggestion
  request_review:
  if: ${{ github.repository_owner == 'PCL-Community' }}
```

2024-04-21 11:12 UTC, Deep-Dark-Forest commented
现在问题太多了，先close了

2024-04-21 11:15 UTC, hejiehao commented on .github/workflows/Start.yml
> +    types: [opened]
```suggestion
    types: [opened, reopened]
```

2024-04-21 11:30 UTC, JingHai-Lingyun reviewed
我写一份... 稍等

2024-04-21 11:32 UTC, hejiehao commented
没有 `pull-requests: write` 权限

2024-04-21 11:42 UTC, Deep-Dark-Forest commented
> 没有 `pull-requests: write` 权限

![Screenshot_20240421_194153_com mmbox xbrowser](https://github.com/PCL-Community/PCL2-1930/assets/131975043/98926604-84f0-40fb-9036-16e744cf4adb)

2024-04-21 12:03 UTC, JingHai-Lingyun commented
Duplicate of #34

2024-04-21 12:05 UTC, Deep-Dark-Forest commented
Duplicate of #34

2024-04-24 14:41 UTC, Deep-Dark-Forest commented
嘿，最近正在尝试用 PAT 来做个bot，应该不会再有权限问题了

2024-04-26 15:05 UTC, JingHai-Lingyun commented
Require Checking

2024-04-30 05:57 UTC, wuliaodexiaoluo approved these changes

2024-05-01 02:12 UTC, Deep-Dark-Forest commented
目前所有的 actions 功能都已测试通过，@WForst-Breeze 是否考虑  Merge ？

2024-05-01 02:12 UTC, WForst-Breeze approved these changes
辛苦了，但是可否在机器人账号 profile 页面标记一下不是我本人的账号（）

2024-05-01 02:13 UTC, JingHai-Lingyun approved these changes

2024-05-01 02:17 UTC, Deep-Dark-Forest commented
> 辛苦了，但是可否在机器人账号 profile 页面标记一下不是我本人的账号（）

Done

2024-05-01 02:22 UTC, merged