优化
WForst-Breeze/PCL2-1930 pull request #47
Opened 2024-05-05 07:38 UTC by allMagicNB

2024-05-05 08:42 UTC, wuliaodexiaoluo commented
https://github.com/Hex-Dragon/PCL2/issues/3792#issue-2279395271
等待龙猫确认

2024-05-06 04:57 UTC, allMagicNB commented
等个屁，哪个客户端作者会闲得蛋疼改 OptiFine？

2024-05-06 05:56 UTC, wuliaodexiaoluo commented
你确定不会有人改客户端？
重点在于关掉校验会不会继续补全 OK

2024-05-06 05:57 UTC, wuliaodexiaoluo commented
@WForst-Breeze wf 有空的话，麻烦你看下要不要等 https://github.com/Hex-Dragon/PCL2/issues/3792#issue-2279395271

2024-05-06 09:09 UTC, wuliaodexiaoluo submitted a review, later dismissed

2024-05-06 09:09 UTC, wuliaodexiaoluo commented on README.md
> + | 无法启动 XXX 客户端 | 可能为其版本 Json 提供的文件大小有误所致，非 PCL 问题。可尝试打开设置中 “关闭文件校验” 开关后再启动。如果还是不能启动且其他启动器均不会出现 PCL 的情况，可以提交反馈。 | #3225
先挪掉，搞不清楚这里关掉是否有效果

2024-05-06 10:51 UTC, WForst-Breeze reviewed
让我再斟酌一下吧（）

2024-05-08 11:16 UTC, WForst-Breeze requested changes

2024-05-08 11:16 UTC, WForst-Breeze commented on README.md
> + | 无法启动 XXX 客户端 | 可能为其版本 Json 提供的文件大小有误所致，非 PCL 问题。可尝试打开设置中 “关闭文件校验” 开关后再启动。如果还是不能启动且其他启动器均不会出现 PCL 的情况，可以提交反馈。 | #3225
我还是更倾向于只写 labymod，因为无法启动 XXX 客户端这个范围太大了（）

或者添加日志可见：文件大小不一致，获取结果为 xxx，要求必须为 xxx。

2024-05-08 11:20 UTC, allMagicNB commented on README.md
> + | 无法启动 XXX 客户端 | 可能为其版本 Json 提供的文件大小有误所致，非 PCL 问题。可尝试打开设置中 “关闭文件校验” 开关后再启动。如果还是不能启动且其他启动器均不会出现 PCL 的情况，可以提交反馈。 | #3225
```suggestion
 | 无法启动 Labymod 客户端 | 为其版本 Json 提供的文件大小有误所致，非 PCL 问题。 | #3225
```

2024-05-08 11:23 UTC, WForst-Breeze approved these changes

2024-05-08 11:35 UTC, merged

2024-05-09 03:42 UTC, wuliaodexiaoluo commented
1930-Web 会在晚些时候同步更新