Update README.md
WForst-Breeze/PCL2-1930 pull request #54
Opened 2024-05-26 13:34 UTC by wuliaodexiaoluo

+1

2024-05-26 21:29 UTC, WForst-Breeze requested changes

2024-05-26 21:29 UTC, WForst-Breeze commented on README.md
> - | Mod 下载详情页加载动画 UI 在加载后未能隐藏 | **[需要社区复现]** 需要开启调试模式的复现日志以显示加载动画 Debug 信息来修复此问题。<br> *搜索关键词：加载动画、加载图标、Mod 下载、列表、UI、隐藏、消失。* | #1624
搜索关键词不要删掉啊

2024-05-26 21:30 UTC, WForst-Breeze commented
下回不要在这个仓库里新建 branch 了，请 Fork 到自己的仓库下再创建 pr

2024-05-27 12:46 UTC, wuliaodexiaoluo commented on README.md
> - | Mod 下载详情页加载动画 UI 在加载后未能隐藏 | **[需要社区复现]** 需要开启调试模式的复现日志以显示加载动画 Debug 信息来修复此问题。<br> *搜索关键词：加载动画、加载图标、Mod 下载、列表、UI、隐藏、消失。* | #1624
等会改

2024-05-27 13:07 UTC, wuliaodexiaoluo commented
主要是，有些 pull request 是在手机上创建的，用 git 并不是很方便（还没签名认证）

2024-05-27 23:22 UTC, WForst-Breeze approved these changes

2024-05-28 10:44 UTC, Deep-Dark-Forest commented
@wuliaodexiaoluo 你可以试试手机网页版……

2024-05-28 11:52 UTC, wuliaodexiaoluo commented
> @wuliaodexiaoluo 你可以试试手机网页版……

对了，GitHub mobile 的 commit 有没有签名，如果有的话我打算之后就用签名来证明这是我的提交

2024-06-01 06:20 UTC, merged