Adding information about Legacy Fabric, Legacy Fabric API, and Babric
WForst-Breeze/PCL2-1930 pull request #7
Opened 2024-03-02 10:12 UTC by Chiloven945

2024-03-02 11:21 UTC, WForst-Breeze commented
有时间来看看，感谢贡献

2024-03-04 13:36 UTC, WForst-Breeze requested changes
抱歉哈，学业有点忙可能不太及时

麻烦照着这几个就改一下就可以了，具体可能得周末才能 Merge，非常感谢！！

2024-03-04 13:36 UTC, WForst-Breeze commented on README.md
> + | 支持安装Legacy Fabric、Legacy Fabric API、Babric等 | 已不再考虑专门为 MC1.9 及以前的版本追加新功能 | #3171 #283
GitHub Mobile 看不太具体英文单词前面有没有空格，如果没有则需要补空格（英文与标点符号之间除外）

MC1.9 → Minecraft 1.9

句末添加句号

2024-03-07 13:57 UTC, Chiloven945 commented
已修改。

2024-03-07 14:04 UTC, merged

2024-03-09 07:10 UTC, WForst-Breeze commented
Done