Update
WForst-Breeze/PCL2-1930 pull request #70
Opened 2024-08-12 08:59 UTC by wuliaodexiaoluo

~失踪人口回归~

2024-08-12 09:21 UTC, Deep-Dark-Forest requested changes, later dismissed

2024-08-12 09:21 UTC, Deep-Dark-Forest commented on README.md
> + | 没有安装重复模组却提示安装了重复模组 | 部分优化模组使用了相同的模组 ID 导致模组加载器误判为相同 Mod，请在安装优化模组前 **仔细核对官方文档/百科** 确认可以同时安装后再安装。| 4376
```suggestion
 | 没有安装重复模组却提示安装了重复模组 | 部分优化模组使用了相同的模组 ID 导致模组加载器误判为相同 Mod，请在安装优化模组前 **仔细核对官方文档/百科** 确认可以同时安装后再安装。| #4376
```

2024-08-12 14:05 UTC, WorldHim commented
其实 mod id 重复也有可能是某个模组内置了另一模组
e.g. create 高版本内置 flywheel

2024-08-12 14:31 UTC, wuliaodexiaoluo commented
>其实 mod id 重复也有可能是某个模组内置了另一模组
e.g. create 高版本内置 flywheel

~Mod 作者一定在玩原神~

2024-08-12 15:00 UTC, Deep-Dark-Forest approved these changes

2024-08-13 03:01 UTC, WForst-Breeze requested changes

2024-08-13 03:01 UTC, WForst-Breeze commented on README.md
> + | 没有安装重复模组却提示安装了重复模组 | 部分优化模组使用了相同的模组 ID 导致模组加载器误判为相同 Mod，请在安装优化模组前 **仔细核对官方文档/百科** 确认可以同时安装后再安装。| #4376
可以搁在「无法加载 Mod 图标」下方

另，为了统一，模组 → Mod

2024-08-13 07:24 UTC, WForst-Breeze approved these changes

2024-08-16 04:59 UTC, merged