Revision
WForst-Breeze/PCL2-1930 pull request #71
Opened 2024-08-16 21:18 UTC by 3gf8jv4dv

2024-08-17 04:59 UTC, Deep-Dark-Forest requested changes

2024-08-17 04:59 UTC, Deep-Dark-Forest commented on ABOUT.md
> +6. 在英文两端添加空格（英文与标点符号之间除外）、引号两端添加空格（引号与其他标点符号之间除外）；
It is unnecessary. “其他” is equal to “其它” in Chinese.

2024-08-17 05:04 UTC, hejiehao commented on ABOUT.md
> +再次强调，我们是为了 PCL 社区和谐发展而相聚的，所以在沟通过程中请务必保证情绪稳定，说句不好听的就是：我没空、也不愿意和处于情绪化的人进行沟通。我希望我们给予这个社区善良，也同样可以得到善良的回报，而非谩骂。
我认为使用逗号会更好，因为“我没空、也不愿意和处于情绪化的人进行沟通。我希望我们给予这个社区善良，也同样可以得到善良的回报，而非谩骂”是“是”的宾语

I think it is better to use comma in this sentence because "我没空、也不愿意和处于情绪化的人进行沟通。我希望我们给予这个社区善良，也同样可以得到善良的回报，而非谩骂" is the object of "是"

2024-08-17 05:08 UTC, wuyuncheng-26 commented on ABOUT.md
> +6. 在英文两端添加空格（英文与标点符号之间除外）、引号两端添加空格（引号与其他标点符号之间除外）；
其它多用于事物，如 **其它符号**
其他可用于人也可用于事物，如 **其他人**

2024-08-17 05:18 UTC, Deep-Dark-Forest requested changes

2024-08-17 05:18 UTC, Deep-Dark-Forest commented on README.md
> + | Minecraft 更新后 PCL 内未找到该最新版本 | 请在 `设置 → 启动器 → 下载 → 版本列表获取` 选择 **尽量使用官方源**。 | #1226
这里我觉得不太适合用代码块……？

2024-08-17 05:18 UTC, Deep-Dark-Forest commented on README.md
> + | 游戏无声音 | 在未静音的情况下，请尝试 `版本设置 → 高级管理 → 补全文件`，若问题仍未解决，则尝试关闭 Windows 防火墙后再试。 | #4368
这里我觉得不太适合用代码块……？

2024-08-17 05:18 UTC, Deep-Dark-Forest commented on README.md
> +若你尚不清楚如何开启调试模式，请开启 `设置 → 启动器 → 调试选项 → 调试模式` 后重启启动器即可。
这里我觉得不太适合用代码块……？

2024-08-17 05:23 UTC, WForst-Breeze requested changes
其它观点同其它 review

2024-08-17 05:23 UTC, WForst-Breeze commented on README.md
> + | `无法搜索到指定 Mod` & `Mod 搜索筛选选项异常` & `Mod 搜索匹配版本错误` & `Mod 详情页前置问题` 等 Mod 搜索问题 | 为 API 或 Mod 作者上传时的设置问题，PCL 无法解决。[^2] | #2352 #2277 #2190 #2069 等 Issues
这个就没必要加了（

2024-08-17 07:04 UTC, wuliaodexiaoluo requested changes

2024-08-17 07:04 UTC, wuliaodexiaoluo commented on ABOUT.md
> +再次强调，我们是为了 PCL 社区和谐发展而相聚的，所以在沟通过程中请务必保证情绪稳定，说句不好听的就是：我没空、也不愿意和处于情绪化的人进行沟通。我希望我们给予这个社区善良，也同样可以得到善良的回报，而非谩骂。
```suggestion
再次强调，我们是为了 PCL 社区和谐发展而相聚的，所以在沟通过程中请务必保证情绪稳定，说句不好听的就是,我没空、也不愿意和处于情绪化的人进行沟通。我希望我们给予这个社区善良，也同样可以得到善良的回报，而非谩骂。
```

我也觉得不太适合

2024-08-17 07:04 UTC, wuliaodexiaoluo commented on README.md
> + | `无法搜索到指定 Mod` & `Mod 搜索筛选选项异常` & `Mod 搜索匹配版本错误` & `Mod 详情页前置问题` 等 Mod 搜索问题 | 为 API 或 Mod 作者上传时的设置问题，PCL 无法解决。[^2] | #2352 #2277 #2190 #2069 等 Issues
```suggestion
 | 无法搜索到指定 Mod & Mod 搜索筛选选项异常 & Mod 搜索匹配版本错误 & Mod 详情页前置问题 等 Mod 搜索问题 | 为 API 或 Mod 作者上传时的设置问题，PCL 无法解决。[^2] | #2352 #2277 #2190 #2069 等 Issues
```

这种非实际展示的文本不建议用代码块

2024-08-17 07:06 UTC, wuliaodexiaoluo commented
>启动 Minecrat 1.7.10-1.12.2 游戏内无声音

>游戏无声音

这两项要不合并到一起？

2024-08-17 07:31 UTC, 3gf8jv4dv commented on ABOUT.md
> +6. 在英文两端添加空格（英文与标点符号之间除外）、引号两端添加空格（引号与其他标点符号之间除外）；
I have encountered arguments about this issue more than once.

Although “其他” and “其它” are listed side by side in dictionaries, their meanings are similar. From the various information and posts I have seen on the Internet, many people still disagree with “其它”, and some dictionary websites only list “其他” instead of “其它”, so I think “其他” should be used first.

I do not care how other people use it in informal settings, but I think there should be a standard agreed upon in formal text, much like ABOUT.md requires spelling conventions for English words.

References:
- [What's the difference between “其他” (qítā) and “其它” (qítā)? - Quora](https://www.quora.com/Whats-the-difference-between-%E2%80%9C%E5%85%B6%E4%BB%96%E2%80%9D-q%C3%ADt%C4%81-and-%E2%80%9C%E5%85%B6%E5%AE%83%E2%80%9D-q%C3%ADt%C4%81)
- [其他 - 维基词典，自由的多语言词典](https://zh.wiktionary.org/wiki/%E5%85%B6%E4%BB%96)
- [其他 - 萌典](https://www.moedict.tw/%E5%85%B6%E4%BB%96)

2024-08-17 07:32 UTC, 3gf8jv4dv commented on ABOUT.md
> +再次强调，我们是为了 PCL 社区和谐发展而相聚的，所以在沟通过程中请务必保证情绪稳定，说句不好听的就是：我没空、也不愿意和处于情绪化的人进行沟通。我希望我们给予这个社区善良，也同样可以得到善良的回报，而非谩骂。
Sure.

2024-08-17 07:33 UTC, 3gf8jv4dv commented on README.md
> + | Minecraft 更新后 PCL 内未找到该最新版本 | 请在 `设置 → 启动器 → 下载 → 版本列表获取` 选择 **尽量使用官方源**。 | #1226
I have the impression that LTCatt uses code blocks at some point... But I will revert it.

2024-08-17 07:34 UTC, 3gf8jv4dv commented on README.md
> + | `无法搜索到指定 Mod` & `Mod 搜索筛选选项异常` & `Mod 搜索匹配版本错误` & `Mod 详情页前置问题` 等 Mod 搜索问题 | 为 API 或 Mod 作者上传时的设置问题，PCL 无法解决。[^2] | #2352 #2277 #2190 #2069 等 Issues
Sure.

2024-08-17 07:46 UTC, 3gf8jv4dv commented
> 这两项要不合并到一起？

These two are actually different issues, but I do not know how to modify this better.

2024-08-17 07:49 UTC, hejiehao commented on ABOUT.md
> +6. 在英文两端添加空格（英文与标点符号之间除外）、引号两端添加空格（引号与其他标点符号之间除外）；
那就使用“其他”。这样子就没有争议了

2024-08-17 07:53 UTC, wuliaodexiaoluo commented
> These two are actually different issues, but I do not know how to modify this better.

Actually, both of these problems are the same steps, first try to press F3+T to reinitialize, then check the audio configuration, and finally check the firewall.
I'll try to merge it together.

2024-08-17 08:10 UTC, Deep-Dark-Forest commented on ABOUT.md
> +6. 在英文两端添加空格（英文与标点符号之间除外）、引号两端添加空格（引号与其他标点符号之间除外）；
事实上，由于此仓库中文件主要是给中国大陆的人看的，我认为应该从中国大陆的资料中寻找答案。
中国大陆比较流行的一个字典，新华字典，中明确表示 `【其它】 同“其他”（用于事物）`。这也就意味着当表示像“标点符号”这样的事物时，使用“其他”与“其它”是一样的。而且我认为在表示事物时“其它”比“其他”更为精确，因为后者的表示范围更大。所以我觉得最好还是保持原样，没有必要更改。

2024-08-17 10:25 UTC, WForst-Breeze commented on ABOUT.md
> +6. 在英文两端添加空格（英文与标点符号之间除外）、引号两端添加空格（引号与其他标点符号之间除外）；
使用此改动，即使用「其他」以避免争议

2024-08-17 10:27 UTC, WForst-Breeze commented
我会在合并前自己再手动将一些地方改一下的，感谢

2024-08-17 10:48 UTC, hejiehao commented on README.md
> +[^1]:请注意，离线账号登录服务器本身违反 [Minecraft 最终用户协议](https://www.minecraft.net/en-us/eula) 提及的 [Minecraft 使用准则](https://www.minecraft.net/en-us/usage-guidelines) 的内容 ( 原文如此：*Access to your server: Must only be
```suggestion
[^1]:请注意，离线账号登录服务器本身违反 [Minecraft 最终用户协议](https://www.minecraft.net/zh-hans/eula) 提及的 [Minecraft 使用准则](https://www.minecraft.net/zh-hans/usage-guidelines) 的内容 ( 原文如此：*Access to your server: Must only be granted to users who have a genuine **paid-for version of Minecraft*** ) ，请谨慎考虑。  
```
改用简体中文，让中国大陆玩家更容易读懂

2024-08-19 10:49 UTC, WForst-Breeze approved these changes

2024-08-19 10:50 UTC, merged