移除条目
WForst-Breeze/PCL2-1930 pull request #81
Opened 2024-11-15 03:46 UTC by shimoranla

PCL 已经支持了...
应该没有必要继续挂着了吧

2024-11-15 04:17 UTC, 3gf8jv4dv reviewed
LGTM.

2024-11-15 04:47 UTC, shimoranla commented
> LGTM.

What does that mean?

2024-11-15 04:49 UTC, 3gf8jv4dv commented
> What does that mean?

Oh sorry. I mean looks good to me.

2024-11-15 05:01 UTC, wuliaodexiaoluo commented
>What does that mean?

算是一种业内黑话，表示认可这次更改的意思

Google 的代码审查用语用的就是 LGTM

2024-11-15 05:06 UTC, wuliaodexiaoluo requested changes

2024-11-15 05:06 UTC, wuliaodexiaoluo commented on README.md
> + | Mod 下载详情页加载动画 UI 在加载后未能隐藏 | **[需要社区复现]**。 <br> *搜索关键词：加载动画、加载图标、Mod 下载、列表、UI、隐藏、消失。* | #1624
```suggestion
 | Mod 下载详情页加载动画 UI 在加载后未能隐藏 | **[需要社区复现]** 需要社区给出稳定的复现方式。 <br> *搜索关键词：加载动画、加载图标、Mod 下载、列表、UI、隐藏、消失。* | #1624
```

2024-11-15 05:09 UTC, wuliaodexiaoluo approved these changes
等待 wf 审阅

2024-11-16 13:25 UTC, WForst-Breeze approved these changes
Review 的有些晚了抱歉，十分感谢

2024-11-17 09:28 UTC, merged