Revision
WForst-Breeze/PCL2-1930 pull request #85
Opened 2024-12-06 17:11 UTC by 3gf8jv4dv

- Revise mod categorization description (issue 277)
- Remove issue 4654 description (this was fixed in PCL 2.8.11)
- Add description of failure to update Release channel version (issue 4965)

2024-12-07 02:06 UTC, wuliaodexiaoluo requested changes

2024-12-07 02:06 UTC, wuliaodexiaoluo commented on README.md
> + | Mod 管理支持分类 Mod | 正在 Discussions 中投票。 | #277 (#5214)
搜索关键词不要删掉

2024-12-07 12:44 UTC, wuliaodexiaoluo approved these changes

2024-12-08 04:10 UTC, WForst-Breeze approved these changes
没有其他问题了，万分感谢www！！

2024-12-08 04:10 UTC, WForst-Breeze commented on README.md
> + | 部分情况下正式版无法更新 | 由于第三方接口问题，部分情况下正式版无法进行更新。详情请见参考条目。 | #4965
条目上移至 *因感染蠕虫病毒……* 条目下方

「详情请见参考条目」可以直接写「详情请见 #4965」即可

2024-12-08 06:23 UTC, 3gf8jv4dv commented on README.md
> + | 部分情况下正式版无法更新 | 由于第三方接口问题，部分情况下正式版无法进行更新。详情请见参考条目。 | #4965
@WForst-Breeze Done.

2024-12-13 15:40 UTC, merged