[Feature] 增加识别客户端/服务端 Mod
WForst-Breeze/PCL2-1930 pull request #87
Opened 2024-12-14 09:12 UTC by wuliaodexiaoluo

2024-12-14 11:07 UTC, WForst-Breeze requested changes

2024-12-14 11:07 UTC, WForst-Breeze commented on README.md
> + | 支持识别和标注客户端/服务端 Mod | 由于 Mod 作者错误标注的情况非常多，实际上无法区分哪些为客户端 Mod，哪些为服务端 Mod | #2467
句末句号

2024-12-14 13:53 UTC, 3gf8jv4dv approved these changes
LGTM.

2024-12-18 04:27 UTC, wuliaodexiaoluo commented
由于增加了部分内容，请重新审查

2024-12-18 14:10 UTC, WForst-Breeze requested changes

2024-12-18 14:10 UTC, WForst-Breeze commented on README.md
> + | 对已安装的 Mod 进行前置缺失 & 版本安装错误 & 重复安装检查 | 正在 Discussion 中投票。 | #5235（#5236）
前面加一个「支持」，即「支持对已安装的……（后同）」

2024-12-18 14:37 UTC, wuliaodexiaoluo commented on README.md
> + | 对已安装的 Mod 进行前置缺失 & 版本安装错误 & 重复安装检查 | 正在 Discussion 中投票。 | #5235（#5236）
> 前面加一个「支持」，即「支持对已安装的……（后同）」

没太看懂啥意思

2024-12-18 14:39 UTC, 3gf8jv4dv commented on README.md
> + | 对已安装的 Mod 进行前置缺失 & 版本安装错误 & 重复安装检查 | 正在 Discussion 中投票。 | #5235（#5236）
我认为你的修订符合他/她的预期。

2024-12-18 14:41 UTC, 3gf8jv4dv approved these changes
LGTM.

2024-12-19 12:33 UTC, WForst-Breeze approved these changes

2024-12-21 09:18 UTC, merged