[Feature] Yggdrasil OAuth & Mod 分组 & 独立网络代理设置 & 添加待加入主页预设的主页
WForst-Breeze/PCL2-1930 pull request #88
Opened 2024-12-18 04:49 UTC by shimoranla

2024-12-18 04:50 UTC, wuliaodexiaoluo approved these changes

2024-12-18 14:07 UTC, WForst-Breeze requested changes
十分感谢~！

2024-12-18 14:07 UTC, WForst-Breeze commented on README.md
> + | 在 Mod 管理为 Mod 添加标签 & 分组 | 正在 Discussions 中投票。 | #277 (#5214)
重复，见第 89 行

2024-12-18 14:07 UTC, WForst-Breeze commented on README.md
> + | 第三方 Yggdrasil 认证服务器 OAuth 登录支持 | 正在 Discussion 中投票，已有相关 Pull Request。 | 🔹 **#5132** <br> #4941 (#4948)
事实上这一条可以放进难检反馈中，感觉不是非常常见👉👈

2024-12-18 14:07 UTC, WForst-Breeze commented on README.md
> + | 支持独立网络代理设置 | 正在 Discussion 中投票。 | #1228 (#1233)
移动至 启动器开机自启动 条目下方

2024-12-18 14:34 UTC, 3gf8jv4dv approved these changes
LGTM.

2024-12-19 15:24 UTC, WForst-Breeze approved these changes

2024-12-21 09:17 UTC, merged