Update README.md
WForst-Breeze/PCL2-1930 pull request #9
Opened 2024-03-10 10:28 UTC by wuliaodexiaoluo

难检新增 PCL 无法更新和解决方案

2024-03-10 15:03 UTC, WForst-Breeze commented
等原 Issue 反馈者回复后我再抽空来看看，感谢贡献~！

2024-03-11 04:36 UTC, wuliaodexiaoluo commented
我感觉这种大爷如果没有发现第二个 Bug 估计是不会来 GitHub 看他发的 Issue

2024-03-18 04:53 UTC, wuliaodexiaoluo commented
Issue 被关了，请问合并还是不合并

2024-03-18 10:47 UTC, WForst-Breeze commented
我这里看 #3505 还没关啊🤔

2024-03-18 13:13 UTC, WForst-Breeze requested changes
先照这个改改看？具体合不合并再观望一下，要是原作者一直不回就不等了

2024-03-18 13:13 UTC, WForst-Breeze commented on README.md
> + | 无法更新 PCL | 请按下 Win+X ，点击 Windows PowerShell（管理员），并输入如下命令 netsh interface ip set dns  "适配器名称" static 8.8.8.8 （请注意，因为排版问题，这条命令直到这里才完全结束，复制过程中除了适配器名称 **需要替换** 外 **其他不可替换** ，除了适配器名称以外其他部分 **不要包含中文字符**
我是用 Github Mobile 看的，可能不太清楚，但从我这里看空格加得有点乱？也可能是显示问题哈

但是可以确定的一点是在英文和数字与标点的连接处无需添加空格，包括加粗文字与标点连接处也不用加空格

2024-03-20 03:50 UTC, wuliaodexiaoluo commented
> 我这里看 #3505 还没关啊🤔

可能是 API 延迟，我已经要求 Collaborator 关闭了

我等会上来看看

2024-03-20 10:45 UTC, WForst-Breeze commented
表格全文使用中文标点符号

2024-03-20 12:13 UTC, WForst-Breeze approved these changes
不等原始 Issue 了，周末 Merge

2024-03-20 12:13 UTC, WForst-Breeze commented on README.md
> + | 无法更新 PCL | 请按下 Win+X ，点击 Windows PowerShell（管理员），并输入如下命令 netsh interface ip set dns  "适配器名称" static 8.8.8.8（请注意，因为排版问题，这条命令直到这里才完全结束，复制过程中除了适配器名称 **需要替换** 外 **其他不可替换**，除了 **适配器名称以外其他部分不要包含中文字符**），
命令部分使用代码块最佳，不弄也没关系，我到时候合并的时候自己改也行

2024-03-20 14:55 UTC, rumengchuxing062 commented on README.md
> + | 无法更新 PCL | 请按下 Win+X ，点击 Windows PowerShell（管理员），并输入如下命令 netsh interface ip set dns  "适配器名称" static 8.8.8.8（请注意，因为排版问题，这条命令直到这里才完全结束，复制过程中除了适配器名称 **需要替换** 外 **其他不可替换**，除了 **适配器名称以外其他部分不要包含中文字符**），
好，待会改改

2024-03-20 15:00 UTC, rumengchuxing062 requested changes
使用代码块标记命令

2024-03-20 15:00 UTC, rumengchuxing062 commented on README.md
> + | 无法更新 PCL | 请按下 Win+X ，点击 Windows PowerShell（管理员），并输入如下命令 netsh interface ip set dns  "适配器名称" static 8.8.8.8（请注意，因为排版问题，这条命令直到这里才完全结束，复制过程中除了适配器名称 **需要替换** 外 **其他不可替换**，除了 **适配器名称以外其他部分不要包含中文字符**），
明天去学校用电脑改，edge mobile没有同步passkey信息，也不支持插件，偏偏我的recover code 还忘记放哪了
我先开个 Change Request 免得忘了

2024-03-20 15:09 UTC, rumengchuxing062 commented
如果没有意外的话明天可能会多两个 Pull Request

2024-03-21 04:12 UTC, wuliaodexiaoluo commented
服了动不动就是冲突

2024-03-21 04:19 UTC, rumengchuxing062 approved these changes

2024-03-21 11:32 UTC, WForst-Breeze requested changes

2024-03-21 11:32 UTC, WForst-Breeze commented on README.md
> + | PCL 日志启动部分出现乱码 | 此为在文件夹插入 Unicode 控制字符而 jlw 不支持 Unicode 控制字符或在 Windows 启用了 UTF-8 解码支持，非 PCL 问题 |  #3236
句末添加句号，句子应为 “此为……所致”，缺了 “所致”

2024-03-21 11:32 UTC, WForst-Breeze commented on README.md
> + | 日志出现 not xxx in java.library.path | Java 不完整，非 PCL 问题，如果可能，请您自行准备 Java 而不是使用自动补全 Java 功能 | #3496
句末添加句号

2024-03-23 05:45 UTC, wuliaodexiaoluo commented
仓库的 about.md 能不能修改
想加这个 [Markdown 中文排版规范](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md)

2024-03-23 08:21 UTC, WForst-Breeze approved these changes

2024-03-23 08:21 UTC, WForst-Breeze commented
> 仓库的 about.md 能不能修改 想加这个 [Markdown 中文排版规范](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md)

不必修改了，谢谢！

2024-03-23 08:22 UTC, merged

2024-03-27 20:36 UTC, allMagicNB commented
#3236 会修，所以应当在修完时删除 “Unicode 控制字符无法被jlw识别” 这条

2024-03-27 23:23 UTC, wuliaodexiaoluo commented
先等两个月，看有没有问题再说
鬼知道龙猫会高出什么新 Bug